Update verify_user_pam.c
neutrinolabs/xrdp pull request #1727
Opened 2020-11-17 03:49 UTC by RisingWater

when a system give a tip message in function verify_pam_conv, authenticate will fail.
so it need skip this message to make sure authenticate success.

2020-11-17 05:38 UTC, metalefty requested changes

2020-11-17 05:38 UTC, metalefty commented on sesman/verify_user_pam.c
> +                memset(&reply[i], 0, sizeof(struct pam_response));
use `g_memset` instead.

2020-11-19 08:22 UTC, metalefty approved these changes
I'm fine with this now.

@matt335672 Any thoughts?

2020-11-19 08:37 UTC, matt335672 commented
Yes, I can see the point of this. I'm happy with the change as suggested. We could log the message from the stack, but I can't see there's really any point.

2020-12-17 07:15 UTC, merged